# Copyright 2020 the v8io authors. All rights reserved. MIT license.

[package]
name = "example"
version = "0.0.1"
edition = "2018"
default-run = "example"

[[bin]]
name = "example"
path = "main.rs"

[dependencies]
rusty_v8 = "0.5.0"
lazy_static = "1.4.0"
libloading = "0.5.0"
